Algoritmo "calcularDivisao"
// Descrição   : Calcular a divisão de dois números.
// Autor(a)    : Lucas M. Gonçalves
// Data atual  : 23/02/2016
Var
   n1, n2, resultado: real

Inicio
      escreva("Informe o primeiro número: ")
      leia(n1)
      escreva("Informe o segundo número: ")
      leia(n2)
      
      resultado:= n1 / n2
      
      escreva("O resultado da divisão é ", resultado)
Fimalgoritmo